language: node_js
node_js:
  - "8"
  - "10"
script:
  - npm run build
notifications:
  email: false
  irc:
    channels:
      - "irc.w3.org#geek"
    skip_join: true
    template:
      - "%{branch} by %{author} (%{build_url}): %{message}"
