language: node_js
node_js:
  - "6"
  - "8"
script:
  - npm test
notifications:
  email: false
  irc:
    channels:
      - "irc.w3.org#sysreq"
    skip_join: true
    template:
      - "%{branch} by %{author} (%{build_url}): %{message}"
